---
#创建秘钥
- hosts: local
  connection: local
  tasks:
  - name: check id_rsa
    local_action: stat path=/root/.ssh/id_rsa
    register: stat_result
  - name: create auth key
    command: ssh-keygen -t rsa -P "" -f /root/.ssh/id_rsa
    when: stat_result.stat.exists == false

#分发秘钥
- hosts: all
  tasks:
  - name: copy ssh key
    authorized_key:
      user: root
      key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
      state: present
      exclusive: yes

#执行角色
- hosts: all
  roles:
  - prepare