---
#创建秘钥
- hosts: local
  connection: local
  tasks:
  - name: check id_rsa
    local_action: stat path=/root/.ssh/id_rsa
    register: stat_result
  - name: create auth key
    command: ssh-keygen -t rsa -P "" -f /root/.ssh/id_rsa
    when: stat_result.stat.exists == false

#分发秘钥
- hosts: all
  tasks:
  - name: copy ssh key
    authorized_key:
      user: root
      key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
      state: present
      exclusive: yes

#准备环境
- hosts: all
  tasks:
  - name: close firewall
    shell: "systemctl stop firewalld.service || true &&\
           systemctl disable firewalld.service || true "
  #禁用selinux
  - name: disabled selinux
    selinux: state=disabled
  #加载bridge、br_netfilter模块，添加配置文件
  - name: load modules
    shell: modprobe bridge && modprobe br_netfilter
  - name: create modules config
    file:
      path: /etc/modules-load.d/k8s.conf
      state: touch
  - name: write k8s.conf
    state: present
    lineinfile:
      dest: /etc/modules-load.d/k8s.conf
      line: "{{ item }}"
    with_items:
    - "bridge"
    - "br_netfilter"
  #设置iptables转发规则
  - name: iptables
    sysctl:
      name: "{{ item }}"
      value: 1
      sysctl_set: yes
      state: present
      reload: yes
    with_items:
    - "net.bridge.bridge-nf-call-iptables"
    - "net.bridge.bridge-nf-call-ip6tables"
  #尽量使用物理内存，不使用虚拟内存
  - name: swappiness
    sysctl:
      name: "vm.swappiness"
      value: 0
      sysctl_set: yes
      state: present
      reload: yes
  #安装必要软件
  - name: install soft
    yum: name={{ item }} state=present
    with_items:
    - nfs-utils
    - epel-release
    - net-tools
    - wget
    - vim
    - ntpdate
    - bash-completion
    - lrzsz
    - zip
    - unzip
    - bridge-utils.x86_64
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
    - rsync
    - telnet
    - apr
    - apr-util
  #安装docker-ce-17.03.2
  - shell: yum-config-manager --add-repo http://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo
  - shell: yum makecache fast -y
  - name: install docker-ce-17.03.2
    yum: name={{ item }} state=present
    with_items:
    - https://download.docker.com/linux/centos/7/x86_64/stable/Packages/docker-ce-selinux-17.03.2.ce-1.el7.centos.noarch.rpm
    - docker-ce-17.03.2.ce-1.el7.centos
  - name: start docker
    shell: systemctl daemon-reload;systemctl enable docker;systemctl start docker
  #安装k8s
  - name: create kubernetes.repo
    file:
      path: /etc/yum.repos.d/kubernetes.repo
      state: touch
  - name: write kubernetes.repo
    lineinfile:
      dest: /etc/yum.repos.d/kubernetes.repo
      line: "{{ item }}"
      state: present
    with_items:
    - '[kubernetes]'
    - 'name=Kubernetes'
    - 'baseurl=https://mirrors.aliyun.com/kubernetes/yum/repos/kubernetes-el7-x86_64/'
    - 'enabled=1'
    - 'gpgcheck=1'
    - 'repo_gpgcheck=1'
    - 'gpgkey=https://mirrors.aliyun.com/kubernetes/yum/doc/yum-key.gpg https://mirrors.aliyun.com/kubernetes/yum/doc/rpm-package-key.gpg'
  - name: install k8s
    yum: name={{ item }} state=present
    with_items:
    - kubelet-1.13.3
    - kubeadm-1.13.3
    - kubectl-1.13.3
  - name: start k8s
    shell: systemctl daemon-reload;systemctl enable kubelet;systemctl start kubelet